version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/repo

    environment:
      # limit memomry usage
      _JAVA_OPTIONS: "-Xms512m -Xmx2048m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

    steps:
      - run:
          name: Lists installed targets
            command: android list target
              environment:
                TERM: dumb

      - run:
          name: Approve license for build tools
            command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - run:
        name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
            environment:
              TERM: dumb

      - checkout

      # run tests!
      - run:
        name: Unit testing
          command: ./gradlew test
            environment:
              TERM: dumb
