version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      # specify the version you desire here
      - image: circleci/android:api-27-alpha

        environment:
          JVM_OPTS: -Xmx3200m

        steps:
          - checkout

          # Download and cache dependencies
          - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

          - run:
              name: chmod permissions
              command: chmod +x ./gradlew

          - run:
              name: Approve license for build tools
              command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses

          - run:
              name: Download Dependencies
              command: ./gradlew androidDependencies

          - save_cache:
              paths:
                - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

          # run tests!
          - run:
              name: Run Tests
              command: ./gradlew test

          - store_artifacts:
              path: app/build/reports
              destination: reports

          - store_test_results:
              path: app/build/test-results
